package com.xudong.dao;

import com.xudong.entity.Relation;

public interface RelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_iot_data_point_relation
     *
     * @mbggenerated Fri Dec 21 14:36:26 CST 2018
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_iot_data_point_relation
     *
     * @mbggenerated Fri Dec 21 14:36:26 CST 2018
     */
    int insert(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_iot_data_point_relation
     *
     * @mbggenerated Fri Dec 21 14:36:26 CST 2018
     */
    int insertSelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_iot_data_point_relation
     *
     * @mbggenerated Fri Dec 21 14:36:26 CST 2018
     */
    Relation selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_iot_data_point_relation
     *
     * @mbggenerated Fri Dec 21 14:36:26 CST 2018
     */
    int updateByPrimaryKeySelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_iot_data_point_relation
     *
     * @mbggenerated Fri Dec 21 14:36:26 CST 2018
     */
    int updateByPrimaryKey(Relation record);
}